services:
  shorty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy # Wait until the postgres service is healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: shorty_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck: # Add a health check to the postgres container
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: shorty_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: docker.io/library/rabbitmq:3.13-management-alpine
    container_name: shorty_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pass
    restart: unless-stopped

volumes:
  pgdata: