services:
  shorty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: shorty_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: shorty_db
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: shorty_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: docker.io/library/rabbitmq:3.13-management-alpine
    container_name: shorty_rabbit
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pass
    restart: unless-stopped

volumes:
  pgdata:

