services:
  shorty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    restart: unless-stopped

  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: shorty_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: shorty_db

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: shorty_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: docker.io/library/rabbitmq:3.13-management-alpine
    container_name: shorty_rabbit
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pass
    restart: unless-stopped

volumes:
  mongodata:

