version: '3.8'

services:
  shorty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: shorty_postgres
    environment:
      POSTGRES_USER: shorty_user
      POSTGRES_PASSWORD: shorty_pass
      POSTGRES_DB: shorty_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: shorty_redis
    ports:

